name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 16
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish to Krypton Repository
        run: gradle publish
        env:
          KRYPTON_REPO_CREDS_USR: ${{ secrets.KRYPTON_REPO_CREDS_USR }}
          KRYPTON_REPO_CREDS_PSW: ${{ secrets.KRYPTON_REPO_CREDS_PSW }}